#!/usr/bin/env bash
set -euo pipefail
project_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
cd "$project_dir"
mkdir -p work/input
protocol=dev/protocols/wlr-virtual-pointer-unstable-v1.xml
wayland-scanner client-header "$protocol" work/input/virtual-pointer.h
wayland-scanner private-code "$protocol" work/input/virtual-pointer.c
cc -Wall -Wextra -O2 -Iwork/input dev/input.c work/input/virtual-pointer.c -o work/input/gooey-input $(pkg-config --cflags --libs wayland-client)
keyboard_protocol=dev/protocols/virtual-keyboard-unstable-v1.xml
wayland-scanner client-header "$keyboard_protocol" work/input/virtual-keyboard.h
wayland-scanner private-code "$keyboard_protocol" work/input/virtual-keyboard.c
cc -Wall -Wextra -O2 -Iwork/input dev/keyboard.c work/input/virtual-keyboard.c -o work/input/gooey-keyboard $(pkg-config --cflags --libs wayland-client xkbcommon)
